language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  # nothing to do, currently
# command to install dependencies
install:
  - pip install -U pip setuptools
  - pip install -U -e ".[test]"
# command to run tests
script:
  - py.test
