language: python
sudo: false
matrix:
    include:
        - os:linux
          python: 3.6
before_install:
  # nothing to do, currently
# command to install dependencies
install:
  - pip install -U pip setuptools pytest tox
  - pip install -U -e "."
# command to run tests
script:
  - tox
